site_name: Overture2HDX
site_description: Library to convert Overture data into GIS formats and upload it to HDX
site_url: "https://github.com/kshitijrajsharma/overture2hdx"

repo_name: "kshitijrajsharma/overture2hdx"
repo_url: "https://github.com/kshitijrajsharma/overture2hdx"
edit_uri: "edit/main/docs/"

extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/kshitijrajsharma/"

theme:
  name: material
  palette:
    primary: custom

extra_css:
  - css/extra.css

markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents

nav:
  - Home: Readme.md